server:
  port: 8000

spring:
  application:
    name: xdclass-order-service

  # 增加 nacos 配置
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.152.129:8848

    # 增加 sentinel 配置
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
        port: 9999

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.152.129:3306/cloud_video?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: admin
    password: 123456

# 控制台输出sql、下划线转驼峰
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# 修改轮询策略
xdclass-video-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule